# Generated by Django 5.2.7 on 2025-10-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('author_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('hashed_password', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
