# Generated by Django 5.2.7 on 2026-01-14 09:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='main.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
