# Generated by Django 5.2.7 on 2025-10-29 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
