# Generated by Django 5.2.7 on 2026-01-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_article_created_date_alter_article_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('technology', 'Технологии'), ('science', 'Наука'), ('sport', 'Спорт'), ('art', 'Искусство'), ('education', 'Образование'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
